input{
	file{
		path=>"/Users/rajatsharma/Desktop/Blackcoffer/ELK_Stack/archive/AB_NYC_2019.csv"
		start_position => "beginning"
		sincedb_path => "/dev/null" 

	}
}
filter{
	csv{
		separator => ","
		columns => ["id","name","host_id","host_name","neighbourhood_group","neighbourhood","latitude","longitude","room_type","price","minimum_nights","number_of_reviews","last_review","reviews_per_month","calculated_host_listings_count","availability_365"]
    	quote_char => '"'
	}
	mutate{
		convert=>{
			"id"=>"integer"
			"host_id"=>"integer"
			"latitude"=>"float"
			"longitude"=>"float"
			"price"=>"integer"
			"minimum_nights"=>"integer"
			"number_of_reviews"=>"integer"
			"reviews_per_month"=>"float"
			"calculated_host_listings_count"=>"integer"
			"availability_365"=>"integer"
		}
	}
	if [last_review]!=""{
		date{
			match=>["last_review","yyyy-MM-dd"]
			target=>"last_review"
		}
	}
}
output{
	elasticsearch{
		hosts => ["http://localhost:9200"]
		index => "ab_nyc_2019"
	}
	stdout {
		codec => rubydebug
	}
}